version: "3"

services:
  library_db:
    image: postgres
    env_file:
      - ./library_back/.env
  library_api:
    build: ./library_back
    command: ["sh", "init.sh"]
    ports:
      - "8000:8000"
    env_file:
      - ./library_back/.env
    depends_on:
      - library_db
      