version: "3"

services:
  library_db:
    image: postgres
    env_file:
      - ./library_back/.env

      
  library_api:
    container_name: library_api
    build:
      context: .
      dockerfile: library_back/Dockerfile
    command: [ "sh", "init.sh" ]
    ports:
      - "8000:8000"
    env_file:
      - ./library_back/.env
    depends_on:
      - library_db


  library_front:
    image: node:lts
    container_name: library_front
    build: ./library_front
    volumes:
      - ./library_front:/library_front
    ports:
      - "3000:3000"
    depends_on:
      - library_api


  nginx:
    image: nginx:1.22.0-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - library_front
      - library_api
      - library_db